title: Astrigot 3D
description: Learn 3D Modeling & Game Asset Creation
baseurl: "/Astrigot3d"  # Note the leading slash
url: "https://astrigot3d.github.io"

collections:
  tutorials:
    output: true # Creates individual pages for each tutorial
    permalink: /tutorials/:path/ # Defines the URL structure
  podcasts: # Add this section
    output: true # Set to true if you want individual pages for each episode
    permalink: /podcast/:title/ # Optional: URL structure for episode pages
    sort_by: date # Optional: Default sorting key